# Generated by Django 5.2.8 on 2025-12-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=6),
        ),
    ]
